defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gps_milonga
  password: gps_milonga
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>

development:
  <<: *defaults
  database: gps_milonga_development

test:
  <<: *defaults
  database: gps_milonga_test

production:
  <<: *defaults
  database: gps_milonga_production
